In [35]:
import pandas as pd

In [36]:
pwd

'/Users/aamirkhan/IronHack/IhClasses/Week3/Project_Olympics/Project1---Ironhack'

In [37]:
df = pd.read_csv('data/raw/athletes.csv')
df

,code,name,name_short,name_tv,gender,function,country_code,country,country_full,nationality,...,family,lang,coach,reason,hero,influence,philosophy,sporting_relatives,ritual,other_sports
0,1532872,ALEKSANYAN Artur,ALEKSANYAN A,Artur ALEKSANYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Father, Gevorg Aleksanyan","Armenian, English, Russian","Gevorg Aleksanyan (ARM), father",He followed his father and his uncle into the ...,"Footballer Zinedine Zidane (FRA), World Cup wi...","His father, Gevorg Aleksanyan","""Wrestling is my life."" (mediamax.am. 18 May 2...",NaN,NaN,NaN
1,1532873,AMOYAN Malkhas,AMOYAN M,Malkhas AMOYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,NaN,Armenian,NaN,NaN,NaN,NaN,"""To become a good athlete, you first have to b...","Uncle, Roman Amoyan (wrestling), 2008 Olympic ...",NaN,NaN
2,1532874,GALSTYAN Slavik,GALSTYAN S,Slavik GALSTYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,NaN,Armenian,Personal: Martin Alekhanyan (ARM).<br>National...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1532944,HARUTYUNYAN Arsen,HARUTYUNYAN A,Arsen HARUTYUNYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Wife, Diana (married October 2022). Daughter, ...",Armenian,National: Habetnak Kurghinyan,While doing karate he noticed wrestlers traini...,"Wrestler Armen Nazaryan (ARM, BUL), two-time O...",NaN,"“Nothing is impossible, set goals in front of ...",NaN,NaN,NaN
4,1532945,TEVANYAN Vazgen,TEVANYAN V,Vazgen TEVANYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Wife, Sona (married November 2023)","Armenian, Russian",National: Habetnak Kurghinyan (ARM),“My family did not like wrestling very much. A...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11105,4982175,JOSEPH Elijah,JOSEPH E,Elijah JOSEPH,Male,Athlete,TTO,Trinidad and Tobago,Trinidad and Tobago,Trinidad and Tobago,...,NaN,English,Personal: Ebert Joseph (TTO),NaN,NaN,NaN,NaN,NaN,NaN,NaN
11106,4982762,HOMAN Khrystyna,HOMAN K,Khrystyna HOMAN,Female,Athlete,UKR,Ukraine,Ukraine,Ukraine,...,Mother and one younger brother,Ukrainian,National: Quedjau Nhabali (UKR).<br>Personal: ...,Because her mother raised the idea,NaN,"""Quedjau Nhabali is always there with the righ...",NaN,NaN,NaN,She likes MMA
11107,4983537,CHELANGAT Annet Chemengich,CHELANGAT AC,Annet Chemengich CHELANGAT,Female,Athlete,UGA,Uganda,Uganda,Uganda,...,NaN,English,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11108,4986655,ADA ETO Sefora,ADA ETO S,Sefora ADA ETO,Female,Athlete,GEQ,Equatorial Guinea,Equatorial Guinea,Equatorial Guinea,...,NaN,Spanish,Personal: Feliciano Javier y Mananses Mba Micha,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11109,9460001,LIUZZI Emanuela,LIUZZI E,Emanuela LIUZZI,Female,Athlete,ITA,Italy,Italy,NaN,...,NaN,Italian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
df.drop(['country_full', 'nationality', 'nationality_full', 'nationality_code', 'name_short', 'name_tv', 'coach', 'reason', 'hero', 'influence', 'philosophy', 'sporting_relatives', 'ritual'], axis=1, inplace=True)
df

,code,name,gender,function,country_code,country,height,weight,disciplines,events,...,birth_country,residence_place,residence_country,nickname,hobbies,occupation,education,family,lang,other_sports
0,1532872,ALEKSANYAN Artur,Male,Athlete,ARM,Armenia,0,0.0,['Wrestling'],"[""Men's Greco-Roman 97kg""]",...,Armenia,GYUMRI,Armenia,White Bear,Playing and watching football,Athlete,Graduated from Shirak State University (Gyumri...,"Father, Gevorg Aleksanyan","Armenian, English, Russian",NaN
1,1532873,AMOYAN Malkhas,Male,Athlete,ARM,Armenia,0,0.0,['Wrestling'],"[""Men's Greco-Roman 77kg""]",...,Armenia,YEREVAN,Armenia,NaN,NaN,NaN,NaN,NaN,Armenian,NaN
2,1532874,GALSTYAN Slavik,Male,Athlete,ARM,Armenia,0,0.0,['Wrestling'],"[""Men's Greco-Roman 67kg""]",...,NaN,YEREVAN,Armenia,NaN,NaN,NaN,NaN,NaN,Armenian,NaN
3,1532944,HARUTYUNYAN Arsen,Male,Athlete,ARM,Armenia,0,0.0,['Wrestling'],"[""Men's Freestyle 57kg""]",...,Armenia,YEREVAN,Armenia,NaN,NaN,Athlete,Graduated with a Master's degree from the Arme...,"Wife, Diana (married October 2022). Daughter, ...",Armenian,NaN
4,1532945,TEVANYAN Vazgen,Male,Athlete,ARM,Armenia,0,0.0,['Wrestling'],"[""Men's Freestyle 65kg""]",...,Armenia,NaN,Armenia,NaN,NaN,Athlete,Studied at the Armenian State Institute of Phy...,"Wife, Sona (married November 2023)","Armenian, Russian",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11105,4982175,JOSEPH Elijah,Male,Athlete,TTO,Trinidad and Tobago,177,0.0,['Athletics'],"[""Men's 4 x 400m Relay""]",...,NaN,NaN,NaN,NaN,NaN,Athlete,NaN,NaN,English,NaN
11106,4982762,HOMAN Khrystyna,Female,Athlete,UKR,Ukraine,0,0.0,['Judo'],['Women +78 kg'],...,Ukraine,KIEV,Ukraine,Danger,"Playing the guitar, eating delicious food, pla...",Athlete,Graduated with a Bachelor's degree in Physical...,Mother and one younger brother,Ukrainian,She likes MMA
11107,4983537,CHELANGAT Annet Chemengich,Female,Athlete,UGA,Uganda,174,0.0,['Athletics'],"[""Women's 10,000m""]",...,Uganda,NaN,Uganda,NaN,NaN,Athlete,NaN,NaN,English,NaN
11108,4986655,ADA ETO Sefora,Female,Athlete,GEQ,Equatorial Guinea,165,0.0,['Athletics'],"[""Women's 100m""]",...,Equatorial Guinea,MALABO,Equatorial Guinea,NaN,NaN,NaN,NaN,NaN,Spanish,NaN
11109,9460001,LIUZZI Emanuela,Female,Athlete,ITA,Italy,0,0.0,['Wrestling'],"[""Women's Freestyle 50kg""]",...,NaN,NaN,NaN,NaN,NaN,Athlete,NaN,NaN,Italian,NaN

In [39]:
print(df['disciplines'].dtype)
print(df['events'].dtype)

object
object

In [47]:
import ast

df['disciplines'] = df['disciplines'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
df['events'] = df['events'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
df

,code,name,gender,function,country_code,country,height,weight,disciplines,events,...,birth_country,residence_place,residence_country,nickname,hobbies,occupation,education,family,lang,other_sports
0,1532872,ALEKSANYAN Artur,Male,Athlete,ARM,Armenia,0,0.0,[Wrestling],[Men's Greco-Roman 97kg],...,Armenia,GYUMRI,Armenia,White Bear,Playing and watching football,Athlete,Graduated from Shirak State University (Gyumri...,"Father, Gevorg Aleksanyan","Armenian, English, Russian",NaN
1,1532873,AMOYAN Malkhas,Male,Athlete,ARM,Armenia,0,0.0,[Wrestling],[Men's Greco-Roman 77kg],...,Armenia,YEREVAN,Armenia,NaN,NaN,NaN,NaN,NaN,Armenian,NaN
2,1532874,GALSTYAN Slavik,Male,Athlete,ARM,Armenia,0,0.0,[Wrestling],[Men's Greco-Roman 67kg],...,NaN,YEREVAN,Armenia,NaN,NaN,NaN,NaN,NaN,Armenian,NaN
3,1532944,HARUTYUNYAN Arsen,Male,Athlete,ARM,Armenia,0,0.0,[Wrestling],[Men's Freestyle 57kg],...,Armenia,YEREVAN,Armenia,NaN,NaN,Athlete,Graduated with a Master's degree from the Arme...,"Wife, Diana (married October 2022). Daughter, ...",Armenian,NaN
4,1532945,TEVANYAN Vazgen,Male,Athlete,ARM,Armenia,0,0.0,[Wrestling],[Men's Freestyle 65kg],...,Armenia,NaN,Armenia,NaN,NaN,Athlete,Studied at the Armenian State Institute of Phy...,"Wife, Sona (married November 2023)","Armenian, Russian",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11105,4982175,JOSEPH Elijah,Male,Athlete,TTO,Trinidad and Tobago,177,0.0,[Athletics],[Men's 4 x 400m Relay],...,NaN,NaN,NaN,NaN,NaN,Athlete,NaN,NaN,English,NaN
11106,4982762,HOMAN Khrystyna,Female,Athlete,UKR,Ukraine,0,0.0,[Judo],[Women +78 kg],...,Ukraine,KIEV,Ukraine,Danger,"Playing the guitar, eating delicious food, pla...",Athlete,Graduated with a Bachelor's degree in Physical...,Mother and one younger brother,Ukrainian,She likes MMA
11107,4983537,CHELANGAT Annet Chemengich,Female,Athlete,UGA,Uganda,174,0.0,[Athletics],"[Women's 10,000m]",...,Uganda,NaN,Uganda,NaN,NaN,Athlete,NaN,NaN,English,NaN
11108,4986655,ADA ETO Sefora,Female,Athlete,GEQ,Equatorial Guinea,165,0.0,[Athletics],[Women's 100m],...,Equatorial Guinea,MALABO,Equatorial Guinea,NaN,NaN,NaN,NaN,NaN,Spanish,NaN
11109,9460001,LIUZZI Emanuela,Female,Athlete,ITA,Italy,0,0.0,[Wrestling],[Women's Freestyle 50kg],...,NaN,NaN,NaN,NaN,NaN,Athlete,NaN,NaN,Italian,NaN

In [41]:
#df[['discipline1', 'discipline2']] = pd.DataFrame(df['disciplines'].tolist(), index=df.index)

In [48]:
#df_exploded_disciplines = df.explode('disciplines')
df_exploded_events = df_exploded_disciplines.explode('events')

In [46]:
df_exploded_events

,code,name,gender,function,country_code,country,height,weight,disciplines,events,...,birth_country,residence_place,residence_country,nickname,hobbies,occupation,education,family,lang,other_sports
0,1532872,ALEKSANYAN Artur,Male,Athlete,ARM,Armenia,0,0.0,Wrestling,Men's Greco-Roman 97kg,...,Armenia,GYUMRI,Armenia,White Bear,Playing and watching football,Athlete,Graduated from Shirak State University (Gyumri...,"Father, Gevorg Aleksanyan","Armenian, English, Russian",NaN
1,1532873,AMOYAN Malkhas,Male,Athlete,ARM,Armenia,0,0.0,Wrestling,Men's Greco-Roman 77kg,...,Armenia,YEREVAN,Armenia,NaN,NaN,NaN,NaN,NaN,Armenian,NaN
2,1532874,GALSTYAN Slavik,Male,Athlete,ARM,Armenia,0,0.0,Wrestling,Men's Greco-Roman 67kg,...,NaN,YEREVAN,Armenia,NaN,NaN,NaN,NaN,NaN,Armenian,NaN
3,1532944,HARUTYUNYAN Arsen,Male,Athlete,ARM,Armenia,0,0.0,Wrestling,Men's Freestyle 57kg,...,Armenia,YEREVAN,Armenia,NaN,NaN,Athlete,Graduated with a Master's degree from the Arme...,"Wife, Diana (married October 2022). Daughter, ...",Armenian,NaN
4,1532945,TEVANYAN Vazgen,Male,Athlete,ARM,Armenia,0,0.0,Wrestling,Men's Freestyle 65kg,...,Armenia,NaN,Armenia,NaN,NaN,Athlete,Studied at the Armenian State Institute of Phy...,"Wife, Sona (married November 2023)","Armenian, Russian",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11105,4982175,JOSEPH Elijah,Male,Athlete,TTO,Trinidad and Tobago,177,0.0,Athletics,Men's 4 x 400m Relay,...,NaN,NaN,NaN,NaN,NaN,Athlete,NaN,NaN,English,NaN
11106,4982762,HOMAN Khrystyna,Female,Athlete,UKR,Ukraine,0,0.0,Judo,Women +78 kg,...,Ukraine,KIEV,Ukraine,Danger,"Playing the guitar, eating delicious food, pla...",Athlete,Graduated with a Bachelor's degree in Physical...,Mother and one younger brother,Ukrainian,She likes MMA
11107,4983537,CHELANGAT Annet Chemengich,Female,Athlete,UGA,Uganda,174,0.0,Athletics,"Women's 10,000m",...,Uganda,NaN,Uganda,NaN,NaN,Athlete,NaN,NaN,English,NaN
11108,4986655,ADA ETO Sefora,Female,Athlete,GEQ,Equatorial Guinea,165,0.0,Athletics,Women's 100m,...,Equatorial Guinea,MALABO,Equatorial Guinea,NaN,NaN,NaN,NaN,NaN,Spanish,NaN
11109,9460001,LIUZZI Emanuela,Female,Athlete,ITA,Italy,0,0.0,Wrestling,Women's Freestyle 50kg,...,NaN,NaN,NaN,NaN,NaN,Athlete,NaN,NaN,Italian,NaN